### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mahimg** [roopansh/Image-Persona#19]
- [x] Add Toasts to the complete App
- [x] Front End Final Touch
- [x] Improve the UI of mobile view. 
- [ ] Add more images to a already formed folder.
- [x] Editing a subfolder name is left.
- [x] Another thing is hiting the CV API to add the tags of the image, which should not take much time.
- [x] Sharing these to the respective person using the link.
- [x] Creating the search bar.
- [x] Form for updating First Name, Last Name along with the profile Pics and Cover Pics.
- [x] Deleting Albums
- [x] Email Authentication
- [x] Backend for searching
- [x] Crop a pic of the user and use that to display instead of folder icon in the subfolders.
- [x] Zip and download albums/images
- [x] Forgot Password Feature
